=== camenduru/inpaint-flux-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Flux.1 DEV ControlNet Inpainting",
      "author": "lllyasviel, Alimama Creative",
      "code": "https://github.com/alimama-creative/FLUX-Controlnet-Inpainting",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/inpaint-flux.ipynb",
      "tags": [
        "Image to Image"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image_check"
    },
    "input_image_check": {
      "type": "string",
      "description": "Input Image URL",
      "widget": "textarea"
    },
    "paint": {
      "type": "string",
      "widget": "paint",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "input_image": "input_image_check",
      "input_mask": "input_mask"
    },
    "input_mask": {
      "type": "string",
      "description": "Input Mask URL",
      "widget": "textarea"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Positive Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "controlnet_strength": {
      "type": "number",
      "description": "ControlNet Strength"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "10",
          "enum": [
            10
          ]
        },
        {
          "description": "15",
          "enum": [
            15
          ]
        },
        {
          "description": "20",
          "enum": [
            20
          ]
        },
        {
          "description": "25",
          "enum": [
            25
          ]
        },
        {
          "description": "30",
          "enum": [
            30
          ]
        }
      ],
      "default": 20
    },
    "guidance": {
      "type": "number",
      "description": "Guidance"
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "beta",
          "enum": [
            "beta"
          ]
        },
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "simple"
    },
    "cfg": {
      "type": "number",
      "description": "CFG"
    },
    "example": {
      "type": "string",
      "image1": "https://files.catbox.moe/7n5qmt.png",
      "image2": "https://files.catbox.moe/78f9vm.png",
      "image3": "https://fakeimg.pl/1024x1024/282828/eae0d0/?text=<in%20out>#.png",
      "image4": "https://files.catbox.moe/ix0ie4.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/inpaint-flux-tost/model.json
{
    "input_image_check": "https://files.catbox.moe/7n5qmt.png",
    "input_mask": "https://files.catbox.moe/78f9vm.png",
    "positive_prompt": "hat",
    "negative_prompt": "bad, ugly, deformed",
    "controlnet_strength": 1.0,
    "seed": 0,
    "steps": 25,
    "guidance": 3.5,
    "sampler_name": "euler",
    "scheduler": "simple",
    "cfg": 1.0
}
